branches:
  only:
    - master
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      a: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      a: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      a: 2
for:
  - matrix:
      only:
        - a: 0
    init:
      - cmake --version
    cache:
      - VTK7.tar
      - VTK7
    install:
      - set path=C:\Python36;%path%
      - echo %path%
      - python --version
      - dir C:\Python36
      - if not exist VTK7 ( python -u _install.py https://www.vtk.org/files/release/7.1/VTK-7.1.1.zip VTK7 )
    build_script:
      - cd
      - if exist VTK7 (
          mkdir build &
          cd build &
          cmake -DVTKBOOL_TESTING=ON -DVTK_DIR=C:\projects\vtkbool\VTK7\lib\cmake\vtk-7.1 -DCMAKE_BUILD_TYPE=Release .. &
          cmake --build . --config Release &
          cd ..
        )
    test_script:
      - if exist build (
          cd build &
          ctest -VV -C Release
        )
  - matrix:
      only:
        - a: 1
    init:
      - cmake --version
    cache:
      - VTK8.tar
      - VTK8
    install:
      - set path=C:\Python37;%path%
      - echo %path%
      - python --version
      - dir C:\Python37
      - if not exist VTK8 ( python -u _install.py https://www.vtk.org/files/release/8.2/VTK-8.2.0.zip VTK8 )
    build_script:
      - cd
      - if exist VTK8 (
          mkdir build &
          cd build &
          cmake -DVTKBOOL_TESTING=ON -DVTK_DIR=C:\projects\vtkbool\VTK8\lib\cmake\vtk-8.2 -DCMAKE_BUILD_TYPE=Release .. &
          cmake --build . --config Release &
          cd ..
        )
    test_script:
      - if exist build (
          cd build &
          ctest -VV -C Release
        )
  - matrix:
      only:
        - a: 2
    install:
      - sudo apt-get update
      - sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
      - sudo apt-get remove -y libpq5
      - sudo apt-get install -y libgdal-dev libpq-dev
      - sudo apt-get install -y libvtk7.1 libvtk7-dev python3-vtk7
      - ls /usr/bin/vtk*
    build_script:
      - mkdir build
      - cd build
      - cmake -DVTKBOOL_TESTING=ON -DCMAKE_BUILD_TYPE=Release ..
      - make
    test_script:
      - ctest
